In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

clientes = pd.read_csv("data/clientes.csv", index_col="customer_id",
                       float_precision="round_trip")

bd = pd.read_csv("data/train.csv", index_col="ID",
                       float_precision="round_trip")

In [14]:
bd.head()

,Total a Pagar,Total Bruto,Total Liquido,Total Imp_,Total Portes,Total Desc_ Global,Total Desc_ Linha,Custo,N_ Detalhes,invoice_count_current_purchase,...,spend_365d,customer_id,payment_type,salesperson,commercial_zone,transport_method,warehouse,document_series,purchase_date,random_noise
ID,,,,,,,,,,,,,,,,,,,,,
10000000,558.11,510.90,453.75,104.36,0.0,0.0,57.15,153.099911,4.0,1.0,...,858.30,660784,Maybe Tomorrow Payment 10,VLOOKUP Master 9,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 61,Final Excel Warehouse 1,Ctrl Z Series 2,2024-10-29,-0.660448
10000001,978.80,830.02,795.77,183.03,0.0,0.0,34.25,472.943134,32.0,1.0,...,2500.68,189146,Maybe Tomorrow Payment 7,VLOOKUP Master 1,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 36,Final Excel Warehouse 1,Ctrl Z Series 1,2017-07-08,0.924510
10000002,10.33,12.00,8.40,1.93,0.0,0.0,3.60,6.097485,1.0,1.0,...,7899.80,103940,Maybe Tomorrow Payment 9,VLOOKUP Master 1,Decorative Dashboard Zone 4,NaN,Final Excel Warehouse 1,Ctrl Z Series 3,2019-03-19,-0.258730
10000003,856.83,696.61,696.61,160.22,0.0,0.0,0.00,408.167275,9.0,1.0,...,270.33,512927,Maybe Tomorrow Payment 7,VLOOKUP Master 4,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 71,Final Excel Warehouse 1,Ctrl Z Series 3,2018-11-10,1.448402
10000004,1616.10,1488.85,1313.90,302.20,0.0,0.0,174.95,485.401864,33.0,1.0,...,2062.50,122356,Maybe Tomorrow Payment 12,NaN,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 61,Final Excel Warehouse 1,Ctrl Z Series 2,2021-11-30,-1.058890

In [15]:
bd.info()

<class 'pandas.DataFrame'>
Index: 6534 entries, 10000000 to 10007674
Data columns (total 38 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Total a Pagar                   6469 non-null   float64
 1   Total Bruto                     6469 non-null   float64
 2   Total Liquido                   6469 non-null   float64
 3   Total Imp_                      6469 non-null   float64
 4   Total Portes                    6469 non-null   float64
 5   Total Desc_ Global              6469 non-null   float64
 6   Total Desc_ Linha               6469 non-null   float64
 7   Custo                           6469 non-null   float64
 8   N_ Detalhes                     6469 non-null   float64
 9   invoice_count_current_purchase  6469 non-null   float64
 10  repeat_purchase_90d             6534 non-null   int64
 11  days_since_previous_purchase    5673 non-null   float64
 12  customer_tenure_days            6469 non-null   float64
 13  prior_purchase_count            6469 non-null   float64
 14  prior_total_spend               6469 non-null   float64
 15  prior_mean_purchase_value       5672 non-null   float64
 16  prior_std_purchase_value        5421 non-null   float64
 17  prior_min_purchase_value        5866 non-null   float64
 18  prior_max_purchase_value        5866 non-null   float64
 19  prior_mean_gap_days             5226 non-null   float64
 20  prior_std_gap_days              5056 non-null   float64
 21  purchase_count_30d              6469 non-null   float64
 22  spend_30d                       6469 non-null   float64
 23  purchase_count_90d              6469 non-null   float64
 24  spend_90d                       6469 non-null   float64
 25  purchase_count_180d             6469 non-null   float64
 26  spend_180d                      6469 non-null   float64
 27  purchase_count_365d             6469 non-null   float64
 28  spend_365d                      6274 non-null   float64
 29  customer_id                     6534 non-null   int64
 30  payment_type                    6274 non-null   str
 31  salesperson                     6275 non-null   str
 32  commercial_zone                 6469 non-null   str
 33  transport_method                6273 non-null   str
 34  warehouse                       6274 non-null   str
 35  document_series                 6469 non-null   str
 36  purchase_date                   6469 non-null   str
 37  random_noise                    6469 non-null   float64
dtypes: float64(29), int64(2), str(7)
memory usage: 1.9 MB

In [20]:
bd.describe(include="all").round(2).T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Total a Pagar,6469.0,NaN,NaN,NaN,925.56,1335.0,0.93,188.92,476.74,1087.67,22297.21
Total Bruto,6469.0,NaN,NaN,NaN,886.15,1327.64,0.83,175.74,445.74,1036.7,21578.28
Total Liquido,6469.0,NaN,NaN,NaN,773.34,1136.36,0.76,154.38,389.91,903.37,18127.81
Total Imp_,6469.0,NaN,NaN,NaN,152.22,225.26,0.0,29.93,79.74,184.84,4169.4
Total Portes,6469.0,NaN,NaN,NaN,1.15,5.84,0.0,0.0,0.0,0.0,181.06
Total Desc_ Global,6469.0,NaN,NaN,NaN,0.35,5.12,0.0,0.0,0.0,0.0,218.49
Total Desc_ Linha,6469.0,NaN,NaN,NaN,112.47,289.99,0.0,0.0,13.13,92.28,4103.44
Custo,6469.0,NaN,NaN,NaN,328.17,519.51,0.0,49.05,152.54,396.06,7427.4
N_ Detalhes,6469.0,NaN,NaN,NaN,21.52,27.71,1.0,4.0,11.0,29.0,423.0
invoice_count_current_purchase,6469.0,NaN,NaN,NaN,1.07,0.31,1.0,1.0,1.0,1.0,5.0
repeat_purchase_90d,6534.0,NaN,NaN,NaN,0.56,0.5,0.0,0.0,1.0,1.0,1.0
days_since_previous_purchase,5673.0,NaN,NaN,NaN,101.53,165.7,-4.0,17.0,57.0,119.0,3199.0
customer_tenure_days,6469.0,NaN,NaN,NaN,1111.38,923.19,0.0,308.0,918.0,1759.0,3506.0
prior_purchase_count,6469.0,NaN,NaN,NaN,23.46,38.34,0.0,3.0,11.0,27.0,276.0
prior_total_spend,6469.0,NaN,NaN,NaN,18908.35,31130.87,0.0,1505.55,6754.31,21642.32,247865.1
prior_mean_purchase_value,5672.0,NaN,NaN,NaN,2821825.32,53041566.66,-2478.66,359.56,724.9,1095.89,1000000000.0
prior_std_purchase_value,5421.0,NaN,NaN,NaN,737.47,666.26,0.0,258.56,569.08,981.09,6770.22
prior_min_purchase_value,5866.0,NaN,NaN,NaN,185.46,408.4,0.93,15.45,64.34,162.61,6298.98
prior_max_purchase_value,5866.0,NaN,NaN,NaN,2946.38,5901.55,3.31,834.53,1783.24,3504.42,267526.19
prior_mean_gap_days,5226.0,NaN,NaN,NaN,95.88,122.59,-4.0,42.6,68.44,113.83,3199.0
prior_std_gap_days,5056.0,NaN,NaN,NaN,74.14,101.82,0.0,32.74,50.64,78.63,2212.54
purchase_count_30d,6469.0,NaN,NaN,NaN,0.6,1.21,0.0,0.0,0.0,1.0,11.0
spend_30d,6469.0,NaN,NaN,NaN,457.14,1191.23,0.0,0.0,0.0,338.24,22297.21
purchase_count_90d,6469.0,NaN,NaN,NaN,1.63,2.98,0.0,0.0,1.0,2.0,22.0
spend_90d,6469.0,NaN,NaN,NaN,1253.53,2347.84,0.0,0.0,198.5,1514.56,30234.88
purchase_count_180d,6469.0,NaN,NaN,NaN,3.37,5.46,0.0,1.0,2.0,3.0,37.0
spend_180d,6469.0,NaN,NaN,NaN,2650.6,4020.27,0.0,149.16,1117.68,3404.44,49746.97
purchase_count_365d,6469.0,NaN,NaN,NaN,6.56,10.33,0.0,1.0,3.0,7.0,60.0
spend_365d,6274.0,NaN,NaN,NaN,2396534.88,48841133.46,-159115.18,637.78,2426.6,7045.42,1000000000.0
customer_id,6534.0,NaN,NaN,NaN,506471.91,266556.04,103940.0,258332.0,489625.0,755628.0,998870.0
payment_type,6274,9,Maybe Tomorrow Payment 7,4565,NaN,NaN,NaN,NaN,NaN,NaN,NaN
salesperson,6275,9,VLOOKUP Master 1,4054,NaN,NaN,NaN,NaN,NaN,NaN,NaN
commercial_zone,6469,5,Decorative Dashboard Zone 4,6260,NaN,NaN,NaN,NaN,NaN,NaN,NaN
transport_method,6273,80,Maybe Tomorrow Delivery 72,1119,NaN,NaN,NaN,NaN,NaN,NaN,NaN
warehouse,6274,2,Final Excel Warehouse 1,6253,NaN,NaN,NaN,NaN,NaN,NaN,NaN
document_series,6469,3,Ctrl Z Series 2,2738,NaN,NaN,NaN,NaN,NaN,NaN,NaN
purchase_date,6469,1492,2015-10-31,52,NaN,NaN,NaN,NaN,NaN,NaN,NaN
random_noise,6469.0,NaN,NaN,NaN,-0.02,1.0,-3.53,-0.68,-0.05,0.64,4.15

In [41]:
#Missing Values
bd.isna().sum()

Total a Pagar                       65
Total Bruto                         65
Total Liquido                       65
Total Imp_                          65
Total Portes                        65
Total Desc_ Global                  65
Total Desc_ Linha                   65
Custo                               65
N_ Detalhes                         65
invoice_count_current_purchase      65
repeat_purchase_90d                  0
days_since_previous_purchase       861
customer_tenure_days                65
prior_purchase_count                65
prior_total_spend                   65
prior_mean_purchase_value          862
prior_std_purchase_value          1113
prior_min_purchase_value           668
prior_max_purchase_value           668
prior_mean_gap_days               1308
prior_std_gap_days                1478
purchase_count_30d                  65
spend_30d                           65
purchase_count_90d                  65
spend_90d                           65
purchase_count_180d                 65
spend_180d                          65
purchase_count_365d                 65
spend_365d                         260
customer_id                          0
payment_type                       260
salesperson                        259
commercial_zone                     65
transport_method                   261
warehouse                          260
document_series                     65
purchase_date                       65
random_noise                        65
dtype: int64

NameError: name 'db' is not defined