In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

clientes = pd.read_csv("data/clientes.csv", index_col="customer_id",
                       float_precision="round_trip")

bd = pd.read_csv("data/train.csv", index_col="customer_id",
                       float_precision="round_trip")

In [14]:
bd.head()

,Total a Pagar,Total Bruto,Total Liquido,Total Imp_,Total Portes,Total Desc_ Global,Total Desc_ Linha,Custo,N_ Detalhes,invoice_count_current_purchase,...,spend_365d,payment_type,salesperson,commercial_zone,transport_method,warehouse,document_series,purchase_date,ID,random_noise
customer_id,,,,,,,,,,,,,,,,,,,,,
660784,558.11,510.90,453.75,104.36,0.0,0.0,57.15,153.099911,4.0,1.0,...,858.30,Maybe Tomorrow Payment 10,VLOOKUP Master 9,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 61,Final Excel Warehouse 1,Ctrl Z Series 2,2024-10-29,10000000,-0.660448
189146,978.80,830.02,795.77,183.03,0.0,0.0,34.25,472.943134,32.0,1.0,...,2500.68,Maybe Tomorrow Payment 7,VLOOKUP Master 1,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 36,Final Excel Warehouse 1,Ctrl Z Series 1,2017-07-08,10000001,0.924510
103940,10.33,12.00,8.40,1.93,0.0,0.0,3.60,6.097485,1.0,1.0,...,7899.80,Maybe Tomorrow Payment 9,VLOOKUP Master 1,Decorative Dashboard Zone 4,NaN,Final Excel Warehouse 1,Ctrl Z Series 3,2019-03-19,10000002,-0.258730
512927,856.83,696.61,696.61,160.22,0.0,0.0,0.00,408.167275,9.0,1.0,...,270.33,Maybe Tomorrow Payment 7,VLOOKUP Master 4,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 71,Final Excel Warehouse 1,Ctrl Z Series 3,2018-11-10,10000003,1.448402
122356,1616.10,1488.85,1313.90,302.20,0.0,0.0,174.95,485.401864,33.0,1.0,...,2062.50,Maybe Tomorrow Payment 12,NaN,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 61,Final Excel Warehouse 1,Ctrl Z Series 2,2021-11-30,10000004,-1.058890

In [15]:
bd.info()

<class 'pandas.DataFrame'>
Index: 6534 entries, 660784 to 438652
Data columns (total 38 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Total a Pagar                   6469 non-null   float64
 1   Total Bruto                     6469 non-null   float64
 2   Total Liquido                   6469 non-null   float64
 3   Total Imp_                      6469 non-null   float64
 4   Total Portes                    6469 non-null   float64
 5   Total Desc_ Global              6469 non-null   float64
 6   Total Desc_ Linha               6469 non-null   float64
 7   Custo                           6469 non-null   float64
 8   N_ Detalhes                     6469 non-null   float64
 9   invoice_count_current_purchase  6469 non-null   float64
 10  repeat_purchase_90d             6534 non-null   int64
 11  days_since_previous_purchase    5673 non-null   float64
 12  customer_tenure_days            6469 non-null   float64
 13  prior_purchase_count            6469 non-null   float64
 14  prior_total_spend               6469 non-null   float64
 15  prior_mean_purchase_value       5672 non-null   float64
 16  prior_std_purchase_value        5421 non-null   float64
 17  prior_min_purchase_value        5866 non-null   float64
 18  prior_max_purchase_value        5866 non-null   float64
 19  prior_mean_gap_days             5226 non-null   float64
 20  prior_std_gap_days              5056 non-null   float64
 21  purchase_count_30d              6469 non-null   float64
 22  spend_30d                       6469 non-null   float64
 23  purchase_count_90d              6469 non-null   float64
 24  spend_90d                       6469 non-null   float64
 25  purchase_count_180d             6469 non-null   float64
 26  spend_180d                      6469 non-null   float64
 27  purchase_count_365d             6469 non-null   float64
 28  spend_365d                      6274 non-null   float64
 29  payment_type                    6274 non-null   str
 30  salesperson                     6275 non-null   str
 31  commercial_zone                 6469 non-null   str
 32  transport_method                6273 non-null   str
 33  warehouse                       6274 non-null   str
 34  document_series                 6469 non-null   str
 35  purchase_date                   6469 non-null   str
 36  ID                              6534 non-null   int64
 37  random_noise                    6469 non-null   float64
dtypes: float64(29), int64(2), str(7)
memory usage: 1.9 MB

In [18]:
bd.describe().round(2).T

,count,mean,std,min,25%,50%,75%,max
Total a Pagar,6469.0,925.56,1335.00,0.93,188.92,476.74,1087.67,2.229721e+04
Total Bruto,6469.0,886.15,1327.64,0.83,175.74,445.74,1036.70,2.157828e+04
Total Liquido,6469.0,773.34,1136.36,0.76,154.38,389.91,903.37,1.812781e+04
Total Imp_,6469.0,152.22,225.26,0.00,29.93,79.74,184.84,4.169400e+03
Total Portes,6469.0,1.15,5.84,0.00,0.00,0.00,0.00,1.810600e+02
Total Desc_ Global,6469.0,0.35,5.12,0.00,0.00,0.00,0.00,2.184900e+02
Total Desc_ Linha,6469.0,112.47,289.99,0.00,0.00,13.13,92.28,4.103440e+03
Custo,6469.0,328.17,519.51,0.00,49.05,152.54,396.06,7.427400e+03
N_ Detalhes,6469.0,21.52,27.71,1.00,4.00,11.00,29.00,4.230000e+02
invoice_count_current_purchase,6469.0,1.07,0.31,1.00,1.00,1.00,1.00,5.000000e+00
repeat_purchase_90d,6534.0,0.56,0.50,0.00,0.00,1.00,1.00,1.000000e+00
days_since_previous_purchase,5673.0,101.53,165.70,-4.00,17.00,57.00,119.00,3.199000e+03
customer_tenure_days,6469.0,1111.38,923.19,0.00,308.00,918.00,1759.00,3.506000e+03
prior_purchase_count,6469.0,23.46,38.34,0.00,3.00,11.00,27.00,2.760000e+02
prior_total_spend,6469.0,18908.35,31130.87,0.00,1505.55,6754.31,21642.32,2.478651e+05
prior_mean_purchase_value,5672.0,2821825.32,53041566.66,-2478.66,359.56,724.90,1095.89,1.000000e+09
prior_std_purchase_value,5421.0,737.47,666.26,0.00,258.56,569.08,981.09,6.770220e+03
prior_min_purchase_value,5866.0,185.46,408.40,0.93,15.45,64.34,162.61,6.298980e+03
prior_max_purchase_value,5866.0,2946.38,5901.55,3.31,834.53,1783.24,3504.42,2.675262e+05
prior_mean_gap_days,5226.0,95.88,122.59,-4.00,42.60,68.44,113.83,3.199000e+03
prior_std_gap_days,5056.0,74.14,101.82,0.00,32.74,50.64,78.63,2.212540e+03
purchase_count_30d,6469.0,0.60,1.21,0.00,0.00,0.00,1.00,1.100000e+01
spend_30d,6469.0,457.14,1191.23,0.00,0.00,0.00,338.24,2.229721e+04
purchase_count_90d,6469.0,1.63,2.98,0.00,0.00,1.00,2.00,2.200000e+01
spend_90d,6469.0,1253.53,2347.84,0.00,0.00,198.50,1514.56,3.023488e+04
purchase_count_180d,6469.0,3.37,5.46,0.00,1.00,2.00,3.00,3.700000e+01
spend_180d,6469.0,2650.60,4020.27,0.00,149.16,1117.68,3404.44,4.974697e+04
purchase_count_365d,6469.0,6.56,10.33,0.00,1.00,3.00,7.00,6.000000e+01
spend_365d,6274.0,2396534.88,48841133.46,-159115.18,637.78,2426.60,7045.42,1.000000e+09
ID,6534.0,10003832.50,2218.82,10000000.00,10001911.25,10003824.50,10005759.75,1.000767e+07
random_noise,6469.0,-0.02,1.00,-3.53,-0.68,-0.05,0.64,4.150000e+00