In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# for better resolution plots
%config InlineBackend.figure_format = 'retina'

sns.set_theme()

# Is it worth using
# We need to analyse it and decide if merging it is an option
clientes = pd.read_csv("data/clientes.csv", index_col="customer_id",
                       float_precision="round_trip")

df = pd.read_csv("data/train.csv", index_col="ID",
                       float_precision="round_trip")

In [2]:
print("Database dimensions:")
df.shape

Database dimensions:

(6534, 38)

In [6]:
print("Target variable value counts:")
print(df["repeat_purchase_90d"].value_counts())

print("\nTarget variable percentages:")
print((df["repeat_purchase_90d"].value_counts(normalize=True) * 100).round(2))

Target variable value counts:
repeat_purchase_90d
1    3654
0    2880
Name: count, dtype: int64

Target variable percentages:
repeat_purchase_90d
1    55.92
0    44.08
Name: proportion, dtype: float64

We can see that the database has a decent size (6534 rows) and the target value is decently well distributed.
Our goal is to predict if clients are going to repeat a purchase with the highest hit rate possible.

We have 2 id's the first (ID) iterates all the train database, the second (customer_id) is our foreign key that connects the clients database.

In [11]:
pd.set_option('display.max_columns', None)
df.head(3)

,Total a Pagar,Total Bruto,Total Liquido,Total Imp_,Total Portes,Total Desc_ Global,Total Desc_ Linha,Custo,N_ Detalhes,invoice_count_current_purchase,repeat_purchase_90d,days_since_previous_purchase,customer_tenure_days,prior_purchase_count,prior_total_spend,prior_mean_purchase_value,prior_std_purchase_value,prior_min_purchase_value,prior_max_purchase_value,prior_mean_gap_days,prior_std_gap_days,purchase_count_30d,spend_30d,purchase_count_90d,spend_90d,purchase_count_180d,spend_180d,purchase_count_365d,spend_365d,customer_id,payment_type,salesperson,commercial_zone,transport_method,warehouse,document_series,purchase_date,random_noise
ID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
10000000,558.11,510.90,453.75,104.36,0.0,0.0,57.15,153.099911,4.0,1.0,1,79.0,126.0,2.0,858.30,429.150000,112.656252,349.49,508.81,47.000000,NaN,0.0,0.00,1.0,349.49,2.0,858.30,2.0,858.30,660784,Maybe Tomorrow Payment 10,VLOOKUP Master 9,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 61,Final Excel Warehouse 1,Ctrl Z Series 2,2024-10-29,-0.660448
10000001,978.80,830.02,795.77,183.03,0.0,0.0,34.25,472.943134,32.0,1.0,1,244.0,616.0,5.0,6722.83,1344.566000,1683.795178,84.38,4222.15,93.000000,117.657696,0.0,0.00,0.0,0.00,0.0,0.00,4.0,2500.68,189146,Maybe Tomorrow Payment 7,VLOOKUP Master 1,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 36,Final Excel Warehouse 1,Ctrl Z Series 1,2017-07-08,0.924510
10000002,10.33,12.00,8.40,1.93,0.0,0.0,3.60,6.097485,1.0,1.0,1,9.0,610.0,90.0,17590.08,195.445333,190.389932,4.54,1002.15,6.752809,6.384073,2.0,111.27,9.0,1928.55,28.0,5290.25,49.0,7899.80,103940,Maybe Tomorrow Payment 9,VLOOKUP Master 1,Decorative Dashboard Zone 4,NaN,Final Excel Warehouse 1,Ctrl Z Series 3,2019-03-19,-0.258730

In [10]:
clientes.head(3)

,country_or_region,commercial_region,island,municipality,city,postal_area,postal_code,street,address,customer_type,company_name,customer_since_year
customer_id,,,,,,,,,,,,
842570,Country CT11: Land of The Final Version,Region RG37: We Will See Later,NaN,NaN,City CY417: Missing Cell Port,NaN,Postal code PC828: #REF! Delivery Route,NaN,Address AD1120: Cell Without a Home,NaN,Excel Is Not A Database Ltd 150,2018
770941,Country CT9: Land of The Final Version,NaN,NaN,NaN,NaN,NaN,Postal code PC56: #REF! Delivery Route,NaN,Address AD62: Cell Without a Home,NaN,Excel Is Not A Database Ltd 1064,2021
827053,Country CT10: Land of The Final Version,Region RG17: We Will See Later,Island IS2: The Pivot Archipelago,Municipality MU14: Council of Last Minute Edits,NaN,Postal area PA271: Hidden Sheet Sector,Postal code PC827: #REF! Delivery Route,Street ST170: PowerPoint New Walk,Address AD449: Cell Without a Home,NaN,Excel Is Not A Database Ltd 113,2016

In [7]:
df.info()

<class 'pandas.DataFrame'>
Index: 6534 entries, 10000000 to 10007674
Data columns (total 38 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Total a Pagar                   6469 non-null   float64
 1   Total Bruto                     6469 non-null   float64
 2   Total Liquido                   6469 non-null   float64
 3   Total Imp_                      6469 non-null   float64
 4   Total Portes                    6469 non-null   float64
 5   Total Desc_ Global              6469 non-null   float64
 6   Total Desc_ Linha               6469 non-null   float64
 7   Custo                           6469 non-null   float64
 8   N_ Detalhes                     6469 non-null   float64
 9   invoice_count_current_purchase  6469 non-null   float64
 10  repeat_purchase_90d             6534 non-null   int64
 11  days_since_previous_purchase    5673 non-null   float64
 12  customer_tenure_days            6469 non-null   float64
 13  prior_purchase_count            6469 non-null   float64
 14  prior_total_spend               6469 non-null   float64
 15  prior_mean_purchase_value       5672 non-null   float64
 16  prior_std_purchase_value        5421 non-null   float64
 17  prior_min_purchase_value        5866 non-null   float64
 18  prior_max_purchase_value        5866 non-null   float64
 19  prior_mean_gap_days             5226 non-null   float64
 20  prior_std_gap_days              5056 non-null   float64
 21  purchase_count_30d              6469 non-null   float64
 22  spend_30d                       6469 non-null   float64
 23  purchase_count_90d              6469 non-null   float64
 24  spend_90d                       6469 non-null   float64
 25  purchase_count_180d             6469 non-null   float64
 26  spend_180d                      6469 non-null   float64
 27  purchase_count_365d             6469 non-null   float64
 28  spend_365d                      6274 non-null   float64
 29  customer_id                     6534 non-null   int64
 30  payment_type                    6274 non-null   str
 31  salesperson                     6275 non-null   str
 32  commercial_zone                 6469 non-null   str
 33  transport_method                6273 non-null   str
 34  warehouse                       6274 non-null   str
 35  document_series                 6469 non-null   str
 36  purchase_date                   6469 non-null   str
 37  random_noise                    6469 non-null   float64
dtypes: float64(29), int64(2), str(7)
memory usage: 1.9 MB

In [4]:
df.describe().round(2).T

,count,mean,std,min,25%,50%,75%,max
Total a Pagar,6469.0,925.56,1335.00,0.93,188.92,476.74,1087.67,2.229721e+04
Total Bruto,6469.0,886.15,1327.64,0.83,175.74,445.74,1036.70,2.157828e+04
Total Liquido,6469.0,773.34,1136.36,0.76,154.38,389.91,903.37,1.812781e+04
Total Imp_,6469.0,152.22,225.26,0.00,29.93,79.74,184.84,4.169400e+03
Total Portes,6469.0,1.15,5.84,0.00,0.00,0.00,0.00,1.810600e+02
Total Desc_ Global,6469.0,0.35,5.12,0.00,0.00,0.00,0.00,2.184900e+02
Total Desc_ Linha,6469.0,112.47,289.99,0.00,0.00,13.13,92.28,4.103440e+03
Custo,6469.0,328.17,519.51,0.00,49.05,152.54,396.06,7.427400e+03
N_ Detalhes,6469.0,21.52,27.71,1.00,4.00,11.00,29.00,4.230000e+02
invoice_count_current_purchase,6469.0,1.07,0.31,1.00,1.00,1.00,1.00,5.000000e+00
repeat_purchase_90d,6534.0,0.56,0.50,0.00,0.00,1.00,1.00,1.000000e+00
days_since_previous_purchase,5673.0,101.53,165.70,-4.00,17.00,57.00,119.00,3.199000e+03
customer_tenure_days,6469.0,1111.38,923.19,0.00,308.00,918.00,1759.00,3.506000e+03
prior_purchase_count,6469.0,23.46,38.34,0.00,3.00,11.00,27.00,2.760000e+02
prior_total_spend,6469.0,18908.35,31130.87,0.00,1505.55,6754.31,21642.32,2.478651e+05
prior_mean_purchase_value,5672.0,2821825.32,53041566.66,-2478.66,359.56,724.90,1095.89,1.000000e+09
prior_std_purchase_value,5421.0,737.47,666.26,0.00,258.56,569.08,981.09,6.770220e+03
prior_min_purchase_value,5866.0,185.46,408.40,0.93,15.45,64.34,162.61,6.298980e+03
prior_max_purchase_value,5866.0,2946.38,5901.55,3.31,834.53,1783.24,3504.42,2.675262e+05
prior_mean_gap_days,5226.0,95.88,122.59,-4.00,42.60,68.44,113.83,3.199000e+03
prior_std_gap_days,5056.0,74.14,101.82,0.00,32.74,50.64,78.63,2.212540e+03
purchase_count_30d,6469.0,0.60,1.21,0.00,0.00,0.00,1.00,1.100000e+01
spend_30d,6469.0,457.14,1191.23,0.00,0.00,0.00,338.24,2.229721e+04
purchase_count_90d,6469.0,1.63,2.98,0.00,0.00,1.00,2.00,2.200000e+01
spend_90d,6469.0,1253.53,2347.84,0.00,0.00,198.50,1514.56,3.023488e+04
purchase_count_180d,6469.0,3.37,5.46,0.00,1.00,2.00,3.00,3.700000e+01
spend_180d,6469.0,2650.60,4020.27,0.00,149.16,1117.68,3404.44,4.974697e+04
purchase_count_365d,6469.0,6.56,10.33,0.00,1.00,3.00,7.00,6.000000e+01
spend_365d,6274.0,2396534.88,48841133.46,-159115.18,637.78,2426.60,7045.42,1.000000e+09
customer_id,6534.0,506471.91,266556.04,103940.00,258332.00,489625.00,755628.00,9.988700e+05
random_noise,6469.0,-0.02,1.00,-3.53,-0.68,-0.05,0.64,4.150000e+00

Numerical variables with problems:
N_Detalhes, invoice_count_current_purchase, days_since_previous_purchase, customer_tenure_days, prior_purchase_count, purchase_count_30d, purchase_count_90d, purchase_count_180d, purchase_count_365d should be an int??
Many variables with negative values should be treated! (days_since_previous_purchase, prior_mean_purchase_value,  prior_mean_gap_days, spend_365d)

In [14]:
print(df.describe(include=['str']))

for col in df.select_dtypes(include=['str']).columns:
    print(f"\n{col}:")

    counts = df[col].value_counts(dropna=False)
    percentages = (df[col].value_counts(normalize=True, dropna=False) * 100).round(2)

    print(pd.DataFrame({
        "Count": counts,
        "Percentage (%)": percentages
    }))

                    payment_type       salesperson  \
count                       6274              6275
unique                         9                 9
top     Maybe Tomorrow Payment 7  VLOOKUP Master 1
freq                        4565              4054

                    commercial_zone            transport_method  \
count                          6469                        6273
unique                            5                          80
top     Decorative Dashboard Zone 4  Maybe Tomorrow Delivery 72
freq                           6260                        1119

                      warehouse  document_series purchase_date
count                      6274             6469          6469
unique                        2                3          1492
top     Final Excel Warehouse 1  Ctrl Z Series 2    2015-10-31
freq                       6253             2738            52

payment_type:
                           Count  Percentage (%)
payment_type
Maybe Tomorrow Payment 7    4565           69.87
Maybe Tomorrow Payment 12    991           15.17
Maybe Tomorrow Payment 9     502            7.68
NaN                          260            3.98
Maybe Tomorrow Payment 10    134            2.05
Maybe Tomorrow Payment 8      40            0.61
Maybe Tomorrow Payment 2      21            0.32
Maybe Tomorrow Payment 4       9            0.14
Maybe Tomorrow Payment 11      8            0.12
Maybe Tomorrow Payment 3       4            0.06

salesperson:
                  Count  Percentage (%)
salesperson
VLOOKUP Master 1   4054           62.04
VLOOKUP Master 4   1461           22.36
VLOOKUP Master 9    384            5.88
NaN                 259            3.96
VLOOKUP Master 7    201            3.08
VLOOKUP Master 2    123            1.88
VLOOKUP Master 3     30            0.46
VLOOKUP Master 6     12            0.18
VLOOKUP Master 5      7            0.11
VLOOKUP Master 8      3            0.05

commercial_zone:
                             Count  Percentage (%)
commercial_zone
Decorative Dashboard Zone 4   6260           95.81
Decorative Dashboard Zone 2    151            2.31
NaN                             65            0.99
Decorative Dashboard Zone 3     56            0.86
Decorative Dashboard Zone 6      1            0.02
Decorative Dashboard Zone 7      1            0.02

transport_method:
                            Count  Percentage (%)
transport_method
Maybe Tomorrow Delivery 72   1119           17.13
Maybe Tomorrow Delivery 61    627            9.60
Maybe Tomorrow Delivery 73    445            6.81
Maybe Tomorrow Delivery 59    373            5.71
Maybe Tomorrow Delivery 80    319            4.88
...                           ...             ...
Maybe Tomorrow Delivery 55      1            0.02
Maybe Tomorrow Delivery 58      1            0.02
Maybe Tomorrow Delivery 28      1            0.02
Maybe Tomorrow Delivery 21      1            0.02
Maybe Tomorrow Delivery 23      1            0.02

[81 rows x 2 columns]

warehouse:
                         Count  Percentage (%)
warehouse
Final Excel Warehouse 1   6253           95.70
NaN                        260            3.98
Final Excel Warehouse 3     21            0.32

document_series:
                 Count  Percentage (%)
document_series
Ctrl Z Series 2   2738           41.90
Ctrl Z Series 3   1903           29.12
Ctrl Z Series 1   1828           27.98
NaN                 65            0.99

purchase_date:
               Count  Percentage (%)
purchase_date
NaN               65            0.99
2015-10-31        52            0.80
2018-08-05        46            0.70
2016-07-17        42            0.64
2015-07-12        41            0.63
...              ...             ...
2021-09-03         1            0.02
2024-01-14         1            0.02
2023-09-11         1            0.02
2022-02-18         1            0.02
2024-03-13         1            0.02

[1493 rows x 2 columns]

How should we treat this variables??
Should we do Ordinal our One-hot encoding?
O transport_method devemos poder usar Categorical Encoding

In [20]:
# Duplicates
df.duplicated().sum()

np.int64(10)

In [14]:
# Missing Values
train.isna().sum()

Total a Pagar                       65
Total Bruto                         65
Total Liquido                       65
Total Imp_                          65
Total Portes                        65
Total Desc_ Global                  65
Total Desc_ Linha                   65
Custo                               65
N_ Detalhes                         65
invoice_count_current_purchase      65
repeat_purchase_90d                  0
days_since_previous_purchase       861
customer_tenure_days                65
prior_purchase_count                65
prior_total_spend                   65
prior_mean_purchase_value          862
prior_std_purchase_value          1113
prior_min_purchase_value           668
prior_max_purchase_value           668
prior_mean_gap_days               1308
prior_std_gap_days                1478
purchase_count_30d                  65
spend_30d                           65
purchase_count_90d                  65
spend_90d                           65
purchase_count_180d                 65
spend_180d                          65
purchase_count_365d                 65
spend_365d                         260
customer_id                          0
payment_type                       260
salesperson                        259
commercial_zone                     65
transport_method                   261
warehouse                          260
document_series                     65
purchase_date                       65
random_noise                        65
dtype: int64

In [25]:
null_counts = df.isnull().sum()

cols_65 = null_counts[null_counts == 65].index.tolist()

print("Number of columns:", len(cols_65))
print(cols_65)

Number of columns: 24
['Total a Pagar', 'Total Bruto', 'Total Liquido', 'Total Imp_', 'Total Portes', 'Total Desc_ Global', 'Total Desc_ Linha', 'Custo', 'N_ Detalhes', 'invoice_count_current_purchase', 'customer_tenure_days', 'prior_purchase_count', 'prior_total_spend', 'purchase_count_30d', 'spend_30d', 'purchase_count_90d', 'spend_90d', 'purchase_count_180d', 'spend_180d', 'purchase_count_365d', 'commercial_zone', 'document_series', 'purchase_date', 'random_noise']

In [26]:
df[cols_65].isnull().sum(axis=1).value_counts().sort_index()

0     6469
24      65
Name: count, dtype: int64

In [27]:
df[cols_65].isnull().all(axis=1).sum()

np.int64(65)

In [28]:
mask_65 = df[cols_65].isnull().all(axis=1)

display(df.loc[mask_65])

,Total a Pagar,Total Bruto,Total Liquido,Total Imp_,Total Portes,Total Desc_ Global,Total Desc_ Linha,Custo,N_ Detalhes,invoice_count_current_purchase,repeat_purchase_90d,days_since_previous_purchase,customer_tenure_days,prior_purchase_count,prior_total_spend,prior_mean_purchase_value,prior_std_purchase_value,prior_min_purchase_value,prior_max_purchase_value,prior_mean_gap_days,prior_std_gap_days,purchase_count_30d,spend_30d,purchase_count_90d,spend_90d,purchase_count_180d,spend_180d,purchase_count_365d,spend_365d,customer_id,payment_type,salesperson,commercial_zone,transport_method,warehouse,document_series,purchase_date,random_noise
ID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
10000457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,755628,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10000560,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,755628,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10000678,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,427118,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10000679,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,508217,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10000870,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,427118,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10007151,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,151492,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10007169,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,230585,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10007339,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,902830,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10007583,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,264090,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10007590,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,697676,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN